---
- name: "Install requirements"
  ansible.builtin.package:
    name: unzip
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success

- name: "Install Packer"
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_{{ packer_arch }}.zip
    dest: "{{ packer_install_path }}"
    creates: "{{ packer_install_path }}/packer"
    remote_src: true
    mode: '0755'
